<?php

namespace App\Http\Controllers;

use App\Models\Meeting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MeetingController extends Controller
{
    public function index()
    {
        $meetings = Meeting::where('user_id', Auth::id())
            ->latest()
            ->get();

        return view('meetings.index', compact('meetings'));
    }

    public function create()
    {
        return view('meetings.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'meeting_date' => 'nullable|date',
            'location' => 'nullable|string|max:255',
            'participants' => 'nullable|string',
            'raw_notes' => 'required|string',
        ]);

        Meeting::create([
            'user_id' => Auth::id(),
            'title' => $request->title,
            'meeting_date' => $request->meeting_date,
            'location' => $request->location,
            'participants' => $request->participants,
            'raw_notes' => $request->raw_notes,
            'status' => 'Draft',
        ]);

        return redirect()->route('meetings.index')->with('success', 'Notulensi berhasil dibuat.');
    }

    public function show(Meeting $meeting)
    {
        $this->authorizeMeeting($meeting);

        $meeting->load('actionItems');

        return view('meetings.show', compact('meeting'));
    }

    public function edit(Meeting $meeting)
    {
        $this->authorizeMeeting($meeting);

        return view('meetings.edit', compact('meeting'));
    }

    public function update(Request $request, Meeting $meeting)
    {
        $this->authorizeMeeting($meeting);

        $request->validate([
            'title' => 'required|string|max:255',
            'meeting_date' => 'nullable|date',
            'location' => 'nullable|string|max:255',
            'participants' => 'nullable|string',
            'raw_notes' => 'required|string',
            'status' => 'required|string|max:50',
        ]);

        $meeting->update($request->only([
            'title',
            'meeting_date',
            'location',
            'participants',
            'raw_notes',
            'status',
        ]));

        return redirect()->route('meetings.show', $meeting)->with('success', 'Notulensi berhasil diperbarui.');
    }

    public function destroy(Meeting $meeting)
    {
        $this->authorizeMeeting($meeting);

        $meeting->delete();

        return redirect()->route('meetings.index')->with('success', 'Notulensi berhasil dihapus.');
    }

    public function generateAI(Meeting $meeting)
    {
        $this->authorizeMeeting($meeting);

        $rawNotes = $meeting->raw_notes;

        $aiSummary = "Catatan Rapat yang Dirapikan:\n"
            . ucfirst(trim($rawNotes))
            . "\n\nPoin Pembahasan:\n"
            . "- Catatan rapat telah dirapikan agar lebih mudah dipahami.\n"
            . "- Informasi utama dari catatan mentah digunakan sebagai dasar notulensi.\n"
            . "- Poin penting perlu ditindaklanjuti agar hasil rapat tidak terlupakan.\n\n"
            . "Keputusan:\n"
            . "- Catatan mentah akan dijadikan dasar penyusunan notulensi.\n"
            . "- Tim perlu meninjau kembali hasil notulensi sebelum dibagikan.\n\n"
            . "Tindak Lanjut:\n"
            . "- Meninjau kembali catatan rapat yang sudah dirapikan.\n"
            . "- Menentukan penanggung jawab untuk setiap poin penting.\n"
            . "- Membagikan hasil notulensi kepada peserta rapat.";

        $followUpMessage = "Halo teman-teman, berikut catatan rapat yang sudah dirapikan. Mohon dicek kembali agar setiap poin penting dapat segera ditindaklanjuti.";

        $meeting->update([
            'ai_summary' => $aiSummary,
            'decisions' => "Catatan rapat telah dirapikan dan siap ditinjau kembali.",
            'follow_up_message' => $followUpMessage,
            'health_score' => 80,
            'status' => 'Generated by AI',
        ]);

        $meeting->actionItems()->delete();

        $meeting->actionItems()->create([
            'task' => 'Meninjau kembali catatan rapat yang sudah dirapikan',
            'pic' => 'Koordinator Rapat',
            'deadline' => now()->addDays(1)->format('Y-m-d'),
            'status' => 'Pending',
        ]);

        $meeting->actionItems()->create([
            'task' => 'Menentukan penanggung jawab untuk setiap poin penting',
            'pic' => 'Ketua Tim',
            'deadline' => now()->addDays(2)->format('Y-m-d'),
            'status' => 'Pending',
        ]);

        $meeting->actionItems()->create([
            'task' => 'Membagikan hasil notulensi kepada peserta rapat',
            'pic' => 'Sekretaris',
            'deadline' => now()->addDays(3)->format('Y-m-d'),
            'status' => 'Pending',
        ]);

        return redirect()->route('meetings.show', $meeting)->with('success', 'Catatan rapat berhasil dirapikan oleh AI.');
    }

    private function authorizeMeeting(Meeting $meeting)
    {
        if ($meeting->user_id !== Auth::id()) {
            abort(403);
        }
    }
}
